Traceback (most recent call last):
  File "/Users/alexandruariton/dirktutor3/venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/alexandruariton/dirktutor3/venv/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexandruariton/dirktutor3/venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/alexandruariton/dirktutor3/venv/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/alexandruariton/dirktutor3/venv/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexandruariton/dirktutor3/venv/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!pip install qutip
from qutip import *
import qutip as qt
import numpy as np
import matplotlib.pyplot as plt

#from google.colab import files
from IPython.display import Image
------------------

----- stdout -----
[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1050990d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/qutip/[0m[33m
[0m
----- stdout -----
[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10509ae50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/qutip/[0m[33m
[0m
----- stdout -----
[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10509b4d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/qutip/[0m[33m
[0m
----- stdout -----
[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10509bf10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/qutip/[0m[33m
[0m
----- stdout -----
[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1050ac890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/qutip/[0m[33m
[0m[31mERROR: Could not find a version that satisfies the requirement qutip (from versions: none)[0m[31m
[0m[31mERROR: No matching distribution found for qutip[0m[31m
[0m
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mpip install qutip[39m[38;5;124m'[39m)
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqutip[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mqutip[39;00m [38;5;28;01mas[39;00m [38;5;21;01mqt[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[0;31mModuleNotFoundError[0m: No module named 'qutip'

